// <auto-generated />
using System;
using GestionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240404033814_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionShared.Entities.Actividadad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("investigacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("investigacionId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("GestionShared.Entities.Investigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Investigaciones");
                });

            modelBuilder.Entity("GestionShared.Entities.Investigador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Afiliacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Investigadores");
                });

            modelBuilder.Entity("GestionShared.Entities.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autores")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestigacionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InvestigacionId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("GestionShared.Entities.RecursoEspe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActividadadId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadadId");

                    b.ToTable("RecursosEspe");
                });

            modelBuilder.Entity("InvestigacionInvestigador", b =>
                {
                    b.Property<int>("InvestigacionesAsignadasId")
                        .HasColumnType("int");

                    b.Property<int>("InvestigadoresAsignadosId")
                        .HasColumnType("int");

                    b.HasKey("InvestigacionesAsignadasId", "InvestigadoresAsignadosId");

                    b.HasIndex("InvestigadoresAsignadosId");

                    b.ToTable("InvestigacionInvestigador");
                });

            modelBuilder.Entity("InvestigacionRecursoEspe", b =>
                {
                    b.Property<int>("InvestigacionesId")
                        .HasColumnType("int");

                    b.Property<int>("RecursosEspecializadosId")
                        .HasColumnType("int");

                    b.HasKey("InvestigacionesId", "RecursosEspecializadosId");

                    b.HasIndex("RecursosEspecializadosId");

                    b.ToTable("InvestigacionRecursoEspe");
                });

            modelBuilder.Entity("GestionShared.Entities.Actividadad", b =>
                {
                    b.HasOne("GestionShared.Entities.Investigacion", "investigacion")
                        .WithMany()
                        .HasForeignKey("investigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investigacion");
                });

            modelBuilder.Entity("GestionShared.Entities.Publicacion", b =>
                {
                    b.HasOne("GestionShared.Entities.Investigacion", "Investigacion")
                        .WithMany()
                        .HasForeignKey("InvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigacion");
                });

            modelBuilder.Entity("GestionShared.Entities.RecursoEspe", b =>
                {
                    b.HasOne("GestionShared.Entities.Actividadad", null)
                        .WithMany("RecursosEspecializados")
                        .HasForeignKey("ActividadadId");
                });

            modelBuilder.Entity("InvestigacionInvestigador", b =>
                {
                    b.HasOne("GestionShared.Entities.Investigacion", null)
                        .WithMany()
                        .HasForeignKey("InvestigacionesAsignadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionShared.Entities.Investigador", null)
                        .WithMany()
                        .HasForeignKey("InvestigadoresAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestigacionRecursoEspe", b =>
                {
                    b.HasOne("GestionShared.Entities.Investigacion", null)
                        .WithMany()
                        .HasForeignKey("InvestigacionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionShared.Entities.RecursoEspe", null)
                        .WithMany()
                        .HasForeignKey("RecursosEspecializadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionShared.Entities.Actividadad", b =>
                {
                    b.Navigation("RecursosEspecializados");
                });
#pragma warning restore 612, 618
        }
    }
}
